### ISSUE TITLE
Middleware: Poziv API-ja za unos atrakcija(Quasar/JavaScript) 		- preuzeti i instalirati Quasar,  		- korištenje axios komponente

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2023-turisticke#34]

**Comment by katarinajelacic** [comment]
![image](https://user-images.githubusercontent.com/126498691/229568629-1203a47c-fb00-4e10-8deb-e62407418d65.png)
![image](https://user-images.githubusercontent.com/126498691/229569173-05d11098-287f-464d-8091-9dc2b78cce76.png)

**Comment by vdavid033** [comment]
Probajte maknuti _setup_ iz <script setup>

**Comment by katarinajelacic** [comment]
Jesam, i tako sam riješila da ne javlja više tu grešku, ali mi javlja sad neke druge greške. Sada sam na poslu pa nemam laptop kod sebe, ali donest ću ga danas na predavanje.

**Comment by katarinajelacic** [comment]
![image](https://user-images.githubusercontent.com/126498691/230138887-43ac71df-5ce5-4e7e-af7e-9ab3e83bbbe9.png)

**Comment by vdavid033** [comment]
Quasar je osjetljiv na uvlake i razmake, pa prva greška upozorava da nedostaje uvlaka. I axios se ne koristi pa to javlja kao grešku.

**Comment by vdavid033** [comment]
Riješeno! @katarinajelacic
