### ISSUE TITLE
Korisnik može ocijeniti atrakciju ocjenom 1-5

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2023-turisticke#51]

**Comment by dstaresina** [comment]
Korisnik da bi ocijenio sliku mora na početnom ekranu odabrati željenu atrakciju. Klikom na atrakciju otvara se nova stranica koja sadrži detalje atrakcije. 
Između ostalih detalja atrakcije prikazuje se i ocjena, a ona je prikazana žutim zvjezdicama ( od 1 do 5 zvjezdica).
Ako atrakcija nema ocijene ili želimo izmijeniti ocjenu atrakcije, u padajućem izborniku Ocjena odaberemo brojčanu vrijednost ocijene (od 1 do 5), odmah nakon što smo odabrali vrijednost ona se upisuje u bazu i ažurira se vrijednost na prikazu zvjezdica.

**Comment by dstaresina** [comment]
Ovaj upis ocjene je povezan sa bazom i potpuno je funkcionalan.
